services:
  service-a:
    build: ./service_a
    ports:
      - 3002:3002
    environment:
      OTEL_SERVICE_NAME: service-a
      OTEL_COLLECTOR_SERVER: http://jaeger:4318/v1/traces
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: demo
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/2.sql
      
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"