scrape_configs:
  - job_name: 'service-a'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['service-a:3002']
        labels:
          application: 'Service A'